# -*- coding: utf-8 -*-
"""Assignment 1 Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w48LwnQfizL8sgcKvHwgV6x7z-Q7po4s

**1. Data Loading and Preparation**
"""

# === Cell 1: Import Libraries ===

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: f'{x:.3f}')

# Plot style
sns.set_theme(style='whitegrid', font_scale=1.05)

# === Cell 2: Load Dataset ===

df = pd.read_csv('/content/Smart_Farming_Crop_Yield_2024.csv')

# Preview first five rows
df.head()

# === Cell 3: Basic Dataset Inspection ===

print("Dataset shape:", df.shape)

print("\nData types:")
display(df.dtypes)

print("\nMissing values:")
display(df.isnull().sum())

print("\nDuplicated rows:", df.duplicated().sum())

# === Cell 4: Data Cleaning and Preparation ===

df_clean = df.copy()

# Convert date columns into datetime format
date_cols = ['sowing_date', 'harvest_date', 'timestamp']

for col in date_cols:
    df_clean[col] = pd.to_datetime(df_clean[col], errors='coerce')

# Create crop growth duration
df_clean['growth_days'] = (
    df_clean['harvest_date'] - df_clean['sowing_date']
).dt.days

# Fill missing categorical values with "Unknown"
categorical_missing_cols = ['irrigation_type', 'crop_disease_status']

for col in categorical_missing_cols:
    df_clean[col] = df_clean[col].fillna('Unknown')

# Drop duplicated rows if any
df_clean = df_clean.drop_duplicates()

print("Cleaned dataset shape:", df_clean.shape)

print("\nRemaining missing values:")
display(df_clean.isnull().sum())

# === Cell 5: Define Column Groups ===

numeric_cols = [
    'soil_moisture_%',
    'soil_pH',
    'temperature_C',
    'rainfall_mm',
    'humidity_%',
    'sunlight_hours',
    'pesticide_usage_ml',
    'total_days',
    'yield_kg_per_hectare',
    'latitude',
    'longitude',
    'NDVI_index'
]

categorical_cols = [
    'region',
    'crop_type',
    'irrigation_type',
    'fertilizer_type',
    'crop_disease_status'
]

# Check summary statistics
print("Numerical Summary:")
display(df_clean[numeric_cols].describe())

print("\nCategorical Summary:")
display(df_clean[categorical_cols].describe())

"""**2. Exploratory Data Analysis (EDA)**"""

# === Cell 6: Full Distribution Histograms ===

n_cols = 3
n_rows = int(np.ceil(len(numeric_cols) / n_cols))

fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, 4 * n_rows))
axes = axes.flatten()

for i, col in enumerate(numeric_cols):
    sns.histplot(
        data=df_clean,
        x=col,
        bins=25,
        kde=True,
        stat='percent',
        ax=axes[i]
    )
    axes[i].set_title(f'Distribution of {col}', fontsize=11, fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Percentage (%)')

# Remove empty subplot spaces
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.suptitle('Distribution of Numerical Features', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# === Cell 7: Crop Type Count Breakdown ===

plt.figure(figsize=(8, 5))

crop_order = df_clean['crop_type'].value_counts().index

sns.countplot(
    data=df_clean,
    x='crop_type',
    order=crop_order
)

plt.title('Count of Crop Types', fontsize=14, fontweight='bold')
plt.xlabel('Crop Type')
plt.ylabel('Count')
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

# === Cell 8: Irrigation, Fertilizer and Disease Status Count Breakdown ===

selected_categorical_cols = [
    'irrigation_type',
    'fertilizer_type',
    'crop_disease_status'
]

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for ax, col in zip(axes, selected_categorical_cols):
    order = df_clean[col].value_counts().index

    sns.countplot(
        data=df_clean,
        x=col,
        order=order,
        ax=ax
    )

    ax.set_title(f'Count of {col}', fontsize=12, fontweight='bold')
    ax.set_xlabel(col)
    ax.set_ylabel('Count')
    ax.tick_params(axis='x', rotation=35)

plt.suptitle('Categorical Feature Count Breakdown', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

# === Cell 9: Crop Type Count by Region ===

plt.figure(figsize=(12, 5))

region_order = sorted(df_clean['region'].unique())
crop_order = df_clean['crop_type'].value_counts().index

sns.countplot(
    data=df_clean,
    x='region',
    hue='crop_type',
    order=region_order,
    hue_order=crop_order
)

plt.title('Crop Type Count by Region', fontsize=14, fontweight='bold')
plt.xlabel('Region')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.legend(title='crop_type', loc='upper left')

plt.tight_layout()
plt.show()

# === Cell 10: Total Crop Disease Status Count by Region ===

disease_order = df_clean['crop_disease_status'].value_counts().index

plt.figure(figsize=(12, 6))

sns.countplot(
    data=df_clean,
    x='region',
    hue='crop_disease_status',
    order=region_order,
    hue_order=disease_order
)

plt.title('Total Crop Disease Status Count by Region', fontsize=14, fontweight='bold')
plt.xlabel('Region')
plt.ylabel('Count')
plt.xticks(rotation=30)
plt.legend(title='Crop Disease Status')
plt.tight_layout()
plt.show()

# === Cell 11: Pie Chart of Crop Yield per Hectare by Region ===

yield_by_region = (
    df_clean
    .groupby('region')['yield_kg_per_hectare']
    .sum()
    .sort_values(ascending=False)
)

plt.figure(figsize=(9, 7))

plt.pie(
    yield_by_region,
    labels=yield_by_region.index,
    autopct='%1.2f%%',
    startangle=90,
    wedgeprops={'edgecolor': 'white'}
)

plt.title(
    'Crop Yield in Kilograms per Hectare by Region',
    fontsize=14,
    fontweight='bold'
)

plt.tight_layout()
plt.show()

# === Cell 12: Boxplots of Yield by Categorical Features ===

yield_categorical_cols = [
    'region',
    'crop_type',
    'irrigation_type',
    'fertilizer_type',
    'crop_disease_status'
]

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

for i, col in enumerate(yield_categorical_cols):
    order = df_clean.groupby(col)['yield_kg_per_hectare'].median().sort_values(ascending=False).index

    sns.boxplot(
        data=df_clean,
        x=col,
        y='yield_kg_per_hectare',
        order=order,
        ax=axes[i]
    )

    axes[i].set_title(f'Crop Yield by {col}', fontsize=11, fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Yield (kg/ha)')
    axes[i].tick_params(axis='x', rotation=35)

# Remove unused subplot
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.suptitle(
    'Crop Yield Distribution Across Categorical Features',
    fontsize=16,
    fontweight='bold',
    y=1.02
)

plt.tight_layout()
plt.show()

# === Cell 13: Correlation Heatmap of Numerical Features ===

correlation_cols = [
    'soil_moisture_%',
    'soil_pH',
    'temperature_C',
    'rainfall_mm',
    'humidity_%',
    'sunlight_hours',
    'pesticide_usage_ml',
    'total_days',
    'growth_days',
    'yield_kg_per_hectare',
    'NDVI_index'
]

corr_matrix = df_clean[correlation_cols].corr()

plt.figure(figsize=(12, 9))

sns.heatmap(
    corr_matrix,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    linewidths=0.5,
    square=True
)

plt.title(
    'Correlation Heatmap of Numerical Variables',
    fontsize=14,
    fontweight='bold'
)

plt.tight_layout()
plt.show()

# === Cell 14: Pairplot of Selected Important Variables ===

selected_pairplot_cols = [
    'yield_kg_per_hectare',
    'rainfall_mm',
    'humidity_%',
    'pesticide_usage_ml',
    'soil_moisture_%',
    'NDVI_index'
]

sns.pairplot(
    df_clean[selected_pairplot_cols],
    kind='scatter',
    diag_kind='kde',
    corner=True,
    plot_kws={'alpha': 0.6}
)

plt.suptitle(
    'Pairwise Relationships Among Selected Numerical Variables',
    fontsize=16,
    fontweight='bold',
    y=1.02
)

plt.show()

"""**3. Statistical Hypothesis Testing**"""

# === Cell 15: One-Way ANOVA - Environmental Bands vs Yield ===

from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

df_stat = df_clean.copy()

# Create Low / Medium / High bands using pd.cut
band_variables = {
    'rainfall_mm': 'rainfall_band',
    'humidity_%': 'humidity_band',
    'pesticide_usage_ml': 'pesticide_usage_band',
    'soil_moisture_%': 'soil_moisture_band'
}

for original_col, band_col in band_variables.items():
    bins = [
        df_stat[original_col].min(),
        df_stat[original_col].quantile(1/3),
        df_stat[original_col].quantile(2/3),
        df_stat[original_col].max()
    ]

    df_stat[band_col] = pd.cut(
        df_stat[original_col],
        bins=bins,
        labels=['Low', 'Medium', 'High'],
        include_lowest=True
    )

# Run One-Way ANOVA for each environmental band
for band_col in band_variables.values():
    print(f"\n=== One-Way ANOVA: Yield by {band_col} ===")

    temp = df_stat[[band_col, 'yield_kg_per_hectare']].dropna()

    # Group summary
    summary = (
        temp
        .groupby(band_col, observed=True)['yield_kg_per_hectare']
        .agg(['count', 'mean', 'std', 'median'])
    )
    display(summary.round(3))

    # Prepare groups
    groups = [
        group['yield_kg_per_hectare'].values
        for name, group in temp.groupby(band_col, observed=True)
    ]

    # ANOVA
    f_stat, p_val = stats.f_oneway(*groups)

    print(f"F-statistic: {f_stat:.4f}")
    print(f"p-value: {p_val:.4e}")

    if p_val < 0.05:
        print("Result: Significant difference exists between groups.")

        tukey = pairwise_tukeyhsd(
            endog=temp['yield_kg_per_hectare'],
            groups=temp[band_col],
            alpha=0.05
        )

        print("\nTukey HSD Post-hoc Test:")
        print(tukey)
    else:
        print("Result: No statistically significant difference between groups.")

    # Visualization
    plt.figure(figsize=(7, 4))
    sns.boxplot(
        data=temp,
        x=band_col,
        y='yield_kg_per_hectare',
        order=['Low', 'Medium', 'High']
    )
    plt.title(f'Crop Yield by {band_col}', fontsize=13, fontweight='bold')
    plt.xlabel(band_col)
    plt.ylabel('Yield (kg per hectare)')
    plt.tight_layout()
    plt.show()

# === Cell 16: Chi-Square Test - Environmental Bands vs Crop Disease Status ===

from scipy.stats import chi2_contingency

def cramers_v(contingency_table):
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    n = contingency_table.sum().sum()
    min_dim = min(contingency_table.shape) - 1
    return np.sqrt(chi2 / (n * min_dim))

environmental_bands = [
    'rainfall_band',
    'humidity_band',
    'pesticide_usage_band',
    'soil_moisture_band'
]

for band_col in environmental_bands:
    print(f"\n=== Chi-Square Test: {band_col} vs crop_disease_status ===")

    temp = df_stat[[band_col, 'crop_disease_status']].dropna()

    # Optional: remove Unknown if it represents missing disease status
    temp = temp[temp['crop_disease_status'] != 'Unknown']

    contingency_table = pd.crosstab(
        temp[band_col],
        temp['crop_disease_status']
    )

    display(contingency_table)

    chi2, p_val, dof, expected = chi2_contingency(contingency_table)
    cv = cramers_v(contingency_table)

    print(f"Chi-square statistic: {chi2:.4f}")
    print(f"Degrees of freedom: {dof}")
    print(f"p-value: {p_val:.4e}")
    print(f"Cramer's V: {cv:.4f}")

    if p_val < 0.05:
        print("Result: Significant association exists.")
    else:
        print("Result: No statistically significant association.")

    # Visualization
    plt.figure(figsize=(7, 4))
    sns.countplot(
        data=temp,
        x=band_col,
        hue='crop_disease_status',
        order=['Low', 'Medium', 'High']
    )
    plt.title(f'Crop Disease Status by {band_col}', fontsize=13, fontweight='bold')
    plt.xlabel(band_col)
    plt.ylabel('Count')
    plt.legend(title='Crop Disease Status')
    plt.tight_layout()
    plt.show()

# === Cell 17: Two-Way ANOVA - Fertilizer Type × Irrigation Type on Yield ===

import statsmodels.api as sm
from statsmodels.formula.api import ols

# Prepare data
two_way_df = df_stat[
    ['fertilizer_type', 'irrigation_type', 'yield_kg_per_hectare']
].dropna()

# Remove Unknown irrigation if it was created from missing values
two_way_df = two_way_df[two_way_df['irrigation_type'] != 'Unknown']

# Two-Way ANOVA model
model = ols(
    'yield_kg_per_hectare ~ C(fertilizer_type) * C(irrigation_type)',
    data=two_way_df
).fit()

anova_table = sm.stats.anova_lm(model, typ=2)

print("=== Two-Way ANOVA: Fertilizer Type × Irrigation Type ===")
display(anova_table.round(4))

# Group mean table
print("\nMean Yield by Fertilizer Type and Irrigation Type:")
mean_table = two_way_df.pivot_table(
    values='yield_kg_per_hectare',
    index='fertilizer_type',
    columns='irrigation_type',
    aggfunc='mean'
)

display(mean_table.round(3))

# Interaction plot
plt.figure(figsize=(9, 5))

sns.pointplot(
    data=two_way_df,
    x='fertilizer_type',
    y='yield_kg_per_hectare',
    hue='irrigation_type',
    dodge=True,
    markers='o',
    capsize=0.1,
    errorbar='se'
)

plt.title(
    'Interaction Effect of Fertilizer Type and Irrigation Type on Crop Yield',
    fontsize=13,
    fontweight='bold'
)

plt.xlabel('Fertilizer Type')
plt.ylabel('Mean Yield (kg per hectare)')
plt.legend(title='Irrigation Type')
plt.tight_layout()
plt.show()

# === Cell 18: Shapiro-Wilk Test - Normality of Residuals ===

residuals = model.resid

shapiro_test = stats.shapiro(residuals)

print("=== Shapiro-Wilk Test for Normality of Residuals ===")
print(f"Statistic: {shapiro_test.statistic:.4f}")
print(f"p-value: {shapiro_test.pvalue:.4e}")

if shapiro_test.pvalue > 0.05:
    print("Result: Residuals appear to be normally distributed.")
else:
    print("Result: Residuals do not appear to be normally distributed.")

# Residual distribution plot
plt.figure(figsize=(7, 4))
sns.histplot(residuals, kde=True, bins=25)
plt.title('Distribution of Two-Way ANOVA Residuals', fontsize=13, fontweight='bold')
plt.xlabel('Residuals')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

# === Cell 19: Levene's Test - Homogeneity of Variance ===

# Create groups based on Fertilizer Type × Irrigation Type combination
levene_groups = [
    group['yield_kg_per_hectare'].values
    for name, group in two_way_df.groupby(['fertilizer_type', 'irrigation_type'], observed=True)
    if len(group) > 1
]

levene_test = stats.levene(*levene_groups)

print("=== Levene’s Test for Homogeneity of Variance ===")
print(f"Statistic: {levene_test.statistic:.4f}")
print(f"p-value: {levene_test.pvalue:.4e}")

if levene_test.pvalue > 0.05:
    print("Result: Variances are equal across groups.")
else:
    print("Result: Variances are not equal across groups.")
